---
title: "Instrucciones generales"
lang: es
---


## Descripción

- Las clases se acompañan  de una guía de ejercicios prácticos donde se aplican y profundizan los contenidos de las clases en base a ejercicios con software estadístico, y donde también se abordan otras temáticas relacionadas al manejo y repote de datos. La organización semestral de guías y espacios prácticos se puede revisar en la [planificación del curso](/schedule.html).

## Trabajo con software R

Para los análisis estadísticos de este curso usamos el programa R, en parte porque es gratuito, pero la principal razón es que es de código abierto. Esto quiere decir que cualquier persona puede revisar cómo está hecho y aportar con modificaciones y procedimientos nuevos, como son las librerías que realizan funciones específicas.

El carácter de apertura de R posee muchas ventajas, pero también conlleva complicaciones. Se actualiza permanentemente, así como también las librerías, y esto puede generar problemas de compatibilidad y de fallas en ejecución del código de análisis.

Para minimizar estos posibles problemas en este curso, vamos a:

- trabajar con la misma y última versión de R, que es la [4.4.1](https://www.r-project.org/)
- evitar uso de tilde, ñ, espacios y mayúsculas tanto en carpetas y archivos, así como también en los nombres de las variables

## Sobre errores y consultas sobre problemas con R y ejecución de código

En caso de problemas con ejecución de código, se sugiere intentar solucionarlo autónomamente por no más de 10 minutos, si los problemas siguen entonces consultar. 

El espacio principal de consultas son los foros que se encuentran tanto al final de las guías. El formato de los foros requiere habilitar una cuenta en [Github](https://github.com/).

Al hacer la consulta, adjuntar la siguiente información:

  1. Código completo hasta que se produce el problema
  2. Indicar línea del código donde se produce el problema
  3. Adjuntar el resultado del output de la información de la sesión (output del comando `sessionInfo()`)

### Instalación de R & RStudio {#installR}


Para **instalar R**: ir a [https://cran.r-project.org/index.html](https://cran.r-project.org/index.html) y bajar/instalar la versión correspondiente a la plataforma utilizada (Windows, Mac o Linux)

Para instalar **RStudio**: ir a [https://rstudio.com/products/rstudio/](https://rstudio.com/products/rstudio/) y bajar/instalar RStudio desktop, Open Source License (libre).

En caso de dudas se puede revisar el siguiente **video tutorial** de instalación de R & RStudio, preparado por Julio Iturra (apoyo docente) del curso Estadística Multivariada 2020:

<div style="width: 100%; height: 600px; overflow: hidden;">
<video  style="width: 100%;" controls>
<source src="https://www.dropbox.com/s/goofz32r5htw6pt/tutorialR-4.0.mp4?raw=1" type="video/mp4">
</video>
</div>

Si por alguna razón se prefiere trabajar sin descargar, también se puede utilizar RCloud, abajo un tutorial preparado por Valentina Andrade para el curso de Estadística Multivariada: 

<div style="width: 100%; height: 600px; overflow: hidden;">
<video  style="width: 100%;" controls>
<source src="https://www.dropbox.com/s/6nqm99dqnjvtmry/rcloud.mp4?raw=1" type="video/mp4">
</video>
</div>

### Sobre el trabajo en hojas de código en RStudio {#codigoR}

- El trabajo de análisis en RStudio se efectua en una _hoja de código_ (o R script o sintaxis, o para los usuarios de Stata la _do-file_), que es donde se anotan los comandos y funciones. Para abrir una hoja, en RStudio ir a File > New File > R Script (o ctrl+shift+N),y aparecerá un panel con una pestaña "Untitled" (sin título). Esta es la hoja de código donde se anotan los comandos.

- Los contenidos de las hojas de código son básicamente 2:

  - comandos o funciones: se escriben en la hoja, y para ejecutarlos se debe posicionar el cursor en la línea respectiva y ctrl+enter, el resultado aparecerá en el panel de resultados o _Consola_.
  - texto: para escribir títulos, comentarios, y todo lo que permita entender qué se está haciendo, al principio de la línea respectiva escribir el signo `#`

- Para grabar nuestra hoja de código y así respaldar nuestros análisis, File > Save (o ctrl+s), y dar un nombre al archivo. Recordar: breve, sin espacios ni tildes ni eñes. Por defecto, la extensión de estos archivos es .R

