project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/images/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"
    - "slides/*_files/figure-html"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Estrategias de Investigación Cuantitativa"

website:
  title: "Estrategias de Investigación Cuantitativa"
  site-url: "https://cuantitativa.netlify.app"

 # favicon: "/files/logo-correlacional-transp.png"

  # twitter-card:
  #  image: "/files/social-image-sp23.png"
  #  card-style: summary_large_image
  #  creator: "@andrewheiss"
    # site: "@andrewheiss"

  open-graph:
    image: "/files/logo-correlacional.png" # cambiar luego
    locale: es

  navbar:
    pinned: true
    background: "#1E2D59"
    right:
      - text: "Informaciones"
        file: news/index.qmd
      - schedule.qmd
      - text: "Clases"
     #   file: content/index.qmd
      #- text: "Prácticos"
        file: assignment/index.qmd
      - text: "Trabajos"
        file: trabajos.qmd
      - text: "Recursos"
        file: resource/index.qmd
      - syllabus.qmd
      - icon: cloud-fill
        href: "https://rstudio.cloud"
        aria-label: RStudio.cloud

  sidebar:
    - title: "Clases"
      style: "docked"
      search: false
      lang: es
      background: dark
      contents:
        - text: "Descripción"
          file: content/index.qmd
        - section: "Presentaciones"
          contents:
            - text: "Introducción"
         #     file: content/01-content.qmd
          #  - text: "Inferencia 1"
           #   file: content/02-content.qmd
          #  - text: "Inferencia 2"
           #   file: content/03-content.qmd
            #- text: "Inferencia 3"
             # file: content/04-content.qmd
            #- text: "Inferencia 4"
             # file: content/05-content.qmd
          #  - text: "Inferencia 5"
           #   file: content/06-content.qmd
          #  - text: "Ejercicio Inferencia"
           #   file: content/07-content.qmd
          #  - text: "Bivariada 1"
           #   file: content/08-content.qmd
          #  - text: "Bivariada 2"
           #   file: content/09-content.qmd
            #- text: "Bivariada 3"
            #  file: content/10-content.qmd
            #- text: "Bivariada 4"
             # file: content/11-content.qmd
            #- text: "Bivariada 5"
             # file: content/12-content.qmd
            #- text: "Documentos dinámicos"
             # file: content/13-content.qmd
       # - text: "Foro Clases"
        #  file: content/foro-clases.qmd
   # - title: "Prácticos"
    #  contents:
     #   - text: "Descripción"
      #    file: assignment/index.qmd
       # - section: "Guías"
        #  contents:
          #  - text: "1: Curva Normal e Intervalos de Confianza"
          #    file: assignment/01-practico.qmd
          #  - text: "2: Test de hipótesis"
          #    file: assignment/02-practico.qmd
          #  - text: "3: Correlación de Pearson"
           #   file: assignment/03-practico.qmd
          #  - text: "4- Matrices de correlación, casos perdidos e índices"
          #    file: assignment/04-practico.qmd
           # - text: "5: Asociación entre categóricas"
            #  file: assignment/05-practico.qmd
           # - text: "6: Visualización 1: Tablas"
           #   file: assignment/06-practico.qmd
          #  - text: "7: Gráficos bivariados en reportes dinámicos"
         #     file: assignment/07-practico.qmd
            # - text: "8: Inferencia 4"
            #   file: assignment/08-practico.qmd
            # - text: "9: Reporte - plantilla trabajos"
            #   file: assignment/09-practico.qmd
            # - text: "10: Asociación con categóricas"
            #   file: assignment/10-practico.qmd
            # - text: "CASEN-EBS"
            #   file: assignment/11-practico.qmd
      #  - text: "Foro Prácticos"
       #   file: assignment/foro-practicos.qmd
      #  - text: "Consola R Online"
       #   file: assignment/consola.qmd
    - title: "Recursos"
      contents:
        - text: "Descripción"
          file: resource/index.qmd
        - section: "Guías"
          contents:
            - text: "1: Versiones de R y librerías"
            - file: resource/install.qmd
            - text: "2: Videos tutoriales"
          # - file: resource/videos.qmd
            - text: "3: Glosario de conceptos"
            - file: resource/glosario.qmd
            - text: "4: Varios"
            - file: resource/varios.qmd
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by María Fernanda Núñez <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
