---
title: "Planificación"
sidebar: false
toc: false
page-layout: full
execute:
  freeze: auto 
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

## Forma general de funcionamiento

Este curso se compone de tres actividades principales:

-   <i class="fas fa-chalkboard-teacher"></i> [**Clases lectivas presenciales**](): donde en base a las lecturas correspondientes a esa semana se presentará un resumen de los contenidos principales y se resolverán dudas.

-   <i class="fas fa-user-edit"></i> [**Talleres prácticos**](): 

-   <i class="fas fa-book-reader"></i> [**Lecturas**](): los temas del curso se acompañan de lecturas, las que se encuentras a disposición en esta página.


<br>

+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| ## Presentación                              |                                                                             |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| <font color="orange"> **Agosto** </font>     | <i class="fas fa-chalkboard-teacher"></i> Clases                            | <i class="fas fa-user-edit"></i> Prácticos | <i class="fas fa-book-reader"></i> Lecturas                                                                                                  |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     | [1. Presentación](/content/01-content.html)                                 |                                            | Leer detalladamente [programa del curso](/syllabus.html)                                                                                     |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| <br>                                         | <br>                                                                        |                                            |                                                                                                                                              |
|                                              |                                                                             |                                            |                                                                                                                                              |
| ### UNIDAD 1:                                | ###                                                               |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| <font color="orange"> **Agosto** </font>     | <i class="fas fa-chalkboard-teacher"></i> Clases                            | <i class="fas fa-user-edit"></i> Prácticos | <i class="fas fa-book-reader"></i> Lecturas                                                                                                  |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     | [Datos, probabilidad y distribuciones muestrales](/content/02-content.html) |                                            | \*[Pardo](/files/textos/Pardo.pdf) cap 2 Conceptos previos                                                                                   |
|                                              |                                                                             |                                            |                                                                                                                                              |
|                                              |                                                                             |                                            | [Richtey](/files/textos/Ritchey.pdf) 1-21 : La imaginación estadística                                                                       |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                    | [Error estándar y distribución normal](/content/03-content.html)            |                                            | \*[Richtey](/files/textos/Ritchey.pdf) cap 6                                                                                                 |
|                                              |                                                                             |                                            |                                                                                                                                              |
|                                              |                                                                             |                                            | [Pardo](/files/textos/Pardo.pdf) cap 6 Probabilidad y distribución normal                                                                    |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                  | [Intervalos de confianza](/content/04-content.html)                         |                                            | \*[Richtey](/files/textos/Ritchey.pdf) cap 7 Probabilidad y distribuciones muestrales                                                        |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     | [Test de hipótesis](/content/05-content.html)                               |                                            | \*[Richtey](/files/textos/Ritchey.pdf) cap 8: Intervalos de confianza                                                                        |
|                                              |                                                                             |                                            |                                                                                                                                              |
|                                              |                                                                             |                                            | \*[Richtey](/files/textos/Ritchey.pdf) cap 9: Prueba de hipótesis                                                                            |
|                                              |                                                                             |                                            |                                                                                                                                              |
|                                              |                                                                             |                                            | [Montoya: Los conceptos de especificación y falsación](https://ciencia.lasalle.edu.co/cgi/viewcontent.cgi?article=1063&context=lo)           |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                                             |                        |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| <font color="orange"> **Septiembre** </font> |                                                                             |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
|  Martes                                    | [Hipótesis para una y dos muestras](/content/06-content.html)               |                                            | \*[Richtey](/files/textos/Ritchey.pdf) cap 10: Hipótesis de una muestra                                                                      |
|                                              |                                                                             |                                            |                                                                                                                                              |
|                                              |                                                                             |                                            | \*[Richtey](/files/textos/Ritchey.pdf) cap 11: Hipótesis de dos muestras (prueba t)                                                          |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                      |                                                                             |                       |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     | [Repaso Unidad 1](/content/07-content.html)                                 |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                                |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| ### UNIDAD 2:                                | ###                                                                |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     | [Asociación, covarianza y correlación](/content/08-content.html)            |                                            | [Moore 97-131 Análisis de relaciones](/files/textos/Moore.pdf)                                                                               |
|                                              |                                                                             |                                            |                                                                                                                                              |
|                                              |                                                                             |                                            | [Piovani](/files/textos/Piovani2008.pdf) - The historical construction of correlation                                                        |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                |                                            | [Pardo](/files/textos/Pardo.pdf) 307 - 330 Relación lineal                                                                                   |
|                                              |                                                                             |                                            |                                                                                                                                              |
|                                              |                                                                             |                                            | [Huck](/files/textos/Huck2011ReadingStatisticsandResearch.pdf) 183 - 203 Statistical Inferences Concerning Bivariate Correlation Coefﬁcients |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |            |                                            | [Field](/files/textos/Field-correlation.pdf)                                        |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                      |                                                                             |                         |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                 |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                      |                                                                             |                       |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                  |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                                             |                       |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                               |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                                  |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                                 |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                                 |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| ## Unidad 3:                                 | ##                                                       |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                      |                                                           |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                                             |                 |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                               |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                                             |                      |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                            |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                                                             |                         |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                     |                                       |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Martes                                    |                                                         |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Viernes                                   | Entrega de trabajo final grupal                                             |                                            |                                                                                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+

<br>

## Exámenes finales (orales)

Ver [requisitos de aprobación y eximición](https://cuantitativa.netlify.app/syllabus#requisitos-de-aprobaci%C3%B3n)

-   Examen de primera oportunidad: 

-   Examen de segunda oportunidad: 
