---
title: ""
format: revealjs
editor: visual
---

##  {background-image="../files/img/class-3/UIII-1.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-2.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-3.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-4.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-5.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-6.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-7.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-8.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-9.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-10.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-11.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-12.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-13.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-14.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-15.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-16.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-17.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-18.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-19.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-20.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-21.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-22.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-23.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-24.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-25.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-26.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-27.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-28.jpg" background-size="cover" background-position="center"}

------------------------------------------------------------------------

##  {background-image="../files/img/class-3/UIII-29.jpg" background-size="cover" background-position="center"}
