---
title: "Reporte Notas Prueba 1 - Estadística Correlacional 2024"
date: "2024-09-30"
lang: es
website:
  comments:
    giscus:
      repo: cursos-metodos-facso/correlacional
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE,
                      warning = FALSE)
```

# Prueba 1

## Librerías & datos 

```{r }
pacman::p_load(tidyverse, sjmisc, sjPlot, kableExtra, sjlabelled, readxl, here)
```

```{r echo=FALSE}
#Read google sheets data into R
prueba1 <- read_excel(path = here("files/reporte_notas/notas.xlsx"), sheet = "preguntas")

names(prueba1)

prueba1 <- prueba1 %>% 
  select(3:13, -Puntos, -Justificada) %>% 
  janitor::clean_names() %>% 
  rename_with(.cols = 1:6, .fn = ~ str_replace(., "x", "p")) %>% na.omit()
  
```


## Etiquetados
```{r}
# Label variables

prueba1$p1a <- set_label(x = prueba1$p1a, 
                         label = "Intervalo de Confianza")
prueba1$p1b <- set_label(x = prueba1$p1b, 
                         label = "Error tipo II")
prueba1$p1c <- set_label(x = prueba1$p1c, 
                         label = "Rechazo H0 valor p")
prueba1$p2a <- set_label(x = prueba1$p2a, 
                         label = "Formulación hipótesis")
prueba1$p2b <- set_label(x = prueba1$p2b, 
                         label = "Contraste de prueba t")
prueba1$p2c <- set_label(x = prueba1$p2c, 
                         label = "Intervalo confianza de prueba t")
prueba1$nota <- set_label(x = prueba1$nota, 
                         label = "Nota final")
prueba1$asistida <- set_label(x = prueba1$asistida, 
                         label = "Asistencia Efectiva")
prueba1$asist_total <- set_label(x = prueba1$asist_total, 
                         label = "Asistencia Registrada")
```


## Tabla descriptiva

```{r}
prueba1 %>% descr(., show = c("label","range", "mean", "sd", "n"))%>% kable(.,"markdown", digits=2)
```

## Gráficos descriptivos

```{r}
hist(prueba1$nota)
plot_frq(data = prueba1$nota,type = "hist",show.mean = T)
```


```{r}
prueba1 <- prueba1 %>%  mutate(notas_cat=cut(nota, breaks=c(-Inf,4,5,6, Inf), labels=c("Menor a 4.0","4.0-5.0","5.0-6.0","6.0-7.0")))

frq(prueba1$notas_cat, out="browser", show.na = FALSE, title = "Rangos de notas")

prueba1 <- prueba1 %>% dplyr::select(-notas_cat)
```

## Preguntas y asociaciones

```{r}
tab_corr(prueba1,
         triangle = "lower")
```


```{r}
ggplot(prueba1, aes(x = asist_total, y = nota)) + 
  geom_jitter(width = 0.2, color = "red", size = 4) + 
  labs(title = "Relación entre asistencia y notas en Evaluación 1 (r=0.43)") + 
  labs(x = "Asistencia", y = "Nota") + 
  theme(axis.title = element_text(size = 12),        # Tamaño de las etiquetas de los ejes
        axis.text = element_text(size = 12)) +       # Tamaño del texto de los ejes
  theme(aspect.ratio = 1/1.5) +
  theme(plot.title = element_text(size = 12,         # Tamaño del título
                                  face = "bold",     # Tipo de letra (negrita)
                                  hjust = 0.5)) +
  scale_x_continuous(breaks = seq(1, 12, by = 1), limits = c(1, 12)) +   # Ajuste del eje de asistencia
  scale_y_continuous(breaks = seq(1, 7, by = 1), limits = c(1, 7))       # Ajuste del eje de notas de 1 a 7
```


```{R}
prueba1 <- prueba1 %>%  mutate(asist_total_cat=cut(asist_total, breaks=c(-Inf,7,8,9,10,11,Inf), labels=c("Menos de 8","8","9","10","11","12")))

frq(prueba1$asist_total_cat, out="browser", show.na = FALSE, title = "Asistencia")

prueba1 %>% # se especifica la base de datos
  dplyr::select(asist_total_cat, nota)  %>% # se seleccionan las variables
  dplyr::group_by(Asistencia=sjlabelled::as_label(asist_total_cat)) %>% # se agrupan por la variable categórica y se usan sus etiquetas con as_label
  dplyr::summarise(Obs.=n(),Promedio=round(mean(nota),2),SD=round(sd(nota),2)) %>% # se agregan las operaciones a presentar en la tabla
  kable(, format = "markdown") # se genera la tabla


prueba1 <- prueba1 %>% dplyr::select(-asist_total_cat)
```



**Consistencia interna**

```{r}
pacman::p_load(ltm)

preguntas <- prueba1 %>% dplyr::select(-nota)
cronbach.alpha(na.omit(preguntas))
```
