<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Estadística Correlacional - Inferencia, asociación y reporte">

<title>Práctico 3: Correlación de Pearson – Estadística Correlacional</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="..//files/logo-correlacional-transp.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Práctico 3: Correlación de Pearson – Estadística Correlacional">
<meta property="og:description" content="">
<meta property="og:image" content="https://correlacional.netlify.app/files/logo-correlacional.png">
<meta property="og:site_name" content="Estadística Correlacional">
<meta property="og:locale" content="es">
<meta property="og:image:height" content="533">
<meta property="og:image:width" content="466">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Estadística Correlacional</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../news/index.html"> 
<span class="menu-text">Informaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Planificación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../content/index.html"> 
<span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../assignment/index.html" aria-current="page"> 
<span class="menu-text">Prácticos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resource/index.html"> 
<span class="menu-text">Recursos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://rstudio.cloud"> <i class="bi bi-cloud-fill" role="img" aria-label="RStudio.cloud">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../assignment/01-practico.html">Guías</a></li><li class="breadcrumb-item"><a href="../assignment/03-practico.html">3: Correlación de Pearson</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignment/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Descripción</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Guías</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignment/01-practico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1: Curva Normal e Intervalos de Confianza</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignment/02-practico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2: Test de hipótesis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignment/03-practico.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">3: Correlación de Pearson</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignment/04-practico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4- Matrices de correlación, casos perdidos e índices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignment/05-practico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5: Asociación entre categóricas</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignment/foro-practicos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foro Prácticos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignment/consola.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Consola R Online</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#objetivo-de-la-práctica" id="toc-objetivo-de-la-práctica" class="nav-link active" data-scroll-target="#objetivo-de-la-práctica">Objetivo de la práctica</a>
  <ul class="collapse">
  <li><a href="#recursos-de-la-práctica" id="toc-recursos-de-la-práctica" class="nav-link" data-scroll-target="#recursos-de-la-práctica">Recursos de la práctica</a></li>
  </ul></li>
  <li><a href="#preparación-de-datos" id="toc-preparación-de-datos" class="nav-link" data-scroll-target="#preparación-de-datos">1. Preparación de datos</a></li>
  <li><a href="#correlación-de-pearson" id="toc-correlación-de-pearson" class="nav-link" data-scroll-target="#correlación-de-pearson">2. Correlación de Pearson</a>
  <ul class="collapse">
  <li><a href="#recordemos" id="toc-recordemos" class="nav-link" data-scroll-target="#recordemos">Recordemos…</a></li>
  </ul></li>
  <li><a href="#ejemplo" id="toc-ejemplo" class="nav-link" data-scroll-target="#ejemplo">Ejemplo</a></li>
  <li><a href="#tamaños-de-efecto" id="toc-tamaños-de-efecto" class="nav-link" data-scroll-target="#tamaños-de-efecto">3. Tamaños de efecto</a></li>
  <li><a href="#diagramas-de-dispersión" id="toc-diagramas-de-dispersión" class="nav-link" data-scroll-target="#diagramas-de-dispersión">4. Diagramas de dispersión</a></li>
  <li><a href="#inferencia-en-correlación" id="toc-inferencia-en-correlación" class="nav-link" data-scroll-target="#inferencia-en-correlación">5. Inferencia en correlación</a></li>
  <li><a href="#coeficiente-de-determinación-r2" id="toc-coeficiente-de-determinación-r2" class="nav-link" data-scroll-target="#coeficiente-de-determinación-r2">6. Coeficiente de determinación (<span class="math inline">\(R^2\)</span>)</a></li>
  <li><a href="#limitaciones-de-la-correlación-de-pearson" id="toc-limitaciones-de-la-correlación-de-pearson" class="nav-link" data-scroll-target="#limitaciones-de-la-correlación-de-pearson">7. Limitaciones de la correlación de Pearson</a>
  <ul class="collapse">
  <li><a href="#a-valores-extremos" id="toc-a-valores-extremos" class="nav-link" data-scroll-target="#a-valores-extremos">(a) Valores extremos</a></li>
  <li><a href="#b-distintas-distribuciones" id="toc-b-distintas-distribuciones" class="nav-link" data-scroll-target="#b-distintas-distribuciones">(b) Distintas distribuciones</a></li>
  </ul></li>
  <li><a href="#ejercicio-autónomo" id="toc-ejercicio-autónomo" class="nav-link" data-scroll-target="#ejercicio-autónomo">Ejercicio autónomo</a></li>
  <li><a href="#resolución-ejercicio-autónomo" id="toc-resolución-ejercicio-autónomo" class="nav-link" data-scroll-target="#resolución-ejercicio-autónomo">Resolución ejercicio autónomo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header">
<h1 class="title display-7">Práctico 3: Correlación de Pearson</h1>

<div class="date-block bg-assignment text-white p-2">
  <p class="date">Sesión del martes, 1 de octubre de 2024</p>
</div>
</header>


<section id="objetivo-de-la-práctica" class="level1">
<h1>Objetivo de la práctica</h1>
<p>El propósito de esta guía es introducir el coeficiente de correlación de Pearson como una herramienta para la investigación, enfocándonos en su aplicación en R. A lo largo del ejercicio, aprenderemos a:</p>
<ol type="1">
<li>Preparar los datos,</li>
<li>Estimar el coeficiente de Pearson en R,</li>
<li>Interpretar el tamaño del efecto,</li>
<li>Visualizar la relación entre variables mediante gráficos,</li>
<li>Aplicar la correlación en inferencia estadística,</li>
<li>El rol del coeficiente de determinación, y</li>
<li>Reconocer una las principales limitaciones del coeficiente de Pearson.</li>
</ol>
<p>Utilizaremos un ejemplo que desarrollaremos progresivamente para ilustrar cada paso. Al finalizar, se propondrá un ejercicio autónomo que deberá resolverse de manera individual o grupal, aplicando los conceptos vistos en clases y en esta guía.</p>
<section id="recursos-de-la-práctica" class="level2">
<h2 class="anchored" data-anchor-id="recursos-de-la-práctica">Recursos de la práctica</h2>
<p>En esta práctica trabajaremos con los datos del Estudio Longitudinal Social de Chile (ELSOC) del año 2021, elaborado por <a href="https://coes.cl/encuesta-panel/">COES</a>. Para este ejercicio, obtendremos directamente esta base desde internet. No obstante, también es posible acceder a la misma información a través del siguiente enlace: <a href="https://dataverse.harvard.edu/file.xhtml?fileId=6160180&amp;version=1.0"><i class="fa-solid fa-table" aria-label="table"></i> <code>ELSOC 2021</code></a>. Desde allí, se puede descargar el archivo que contiene la base de datos ELSOC 2021.</p>
</section>
</section>
<section id="preparación-de-datos" class="level1">
<h1>1. Preparación de datos</h1>
<p>Comencemos por preparar nuestros datos. Iniciamos cargando las librerías necesarias.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, <span class="co"># Manipulacion datos</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               sjPlot, <span class="co"># Graficos</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               rstatix, <span class="co"># Test estadísticos</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               broom) <span class="co"># Tablas</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) <span class="co"># para desactivar notacion cientifica</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># para limpiar el entorno de trabajo</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cargamos los datos directamente desde internet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar bbdd pública de ELSOC</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://dataverse.harvard.edu/api/access/datafile/6160180"</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A continuación, exploramos la base de datos <code>elsoc_2021</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(elsoc_2021) <span class="co"># Nombre de columnas</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "idencuesta"         "ola"                "version"           
  [4] "muestra"            "cuestion_mig"       "cuestion_completo" 
  [7] "segmento"           "comuna"             "comuna_cod"        
 [10] "region"             "region_cod"         "estrato"           
 [13] "ponderador01"       "ponderador02"       "fact_exp01"        
 [16] "fact_exp02"         "r01_01"             "r01_02"            
 [19] "r01_03"             "r01_04"             "r01_05"            
 [22] "r01_06"             "r01_07"             "r01_08"            
 [25] "r01_09"             "r01_10"             "r01_11"            
 [28] "r01_12"             "r01_13"             "r03_01"            
 [31] "r03_02"             "r03_03"             "r03_04"            
 [34] "r03_05"             "r03_06"             "r03_07"            
 [37] "r03_08"             "r03_09"             "r04_01"            
 [40] "r04_02"             "r04_03"             "r04_04"            
 [43] "r09"                "r10"                "r11"               
 [46] "r12_01"             "r12_02"             "r12_03"            
 [49] "r12_04"             "r12_05"             "r12_06"            
 [52] "r12_07"             "r16"                "r17"               
 [55] "r18_01"             "r18_02"             "t01"               
 [58] "t05"                "t08"                "t09_01"            
 [61] "t09_02"             "t09_03"             "t10"               
 [64] "t11_01"             "t11_02"             "t11_03"            
 [67] "t11_04"             "t12"                "t14"               
 [70] "c01"                "c02"                "c03"               
 [73] "c04"                "c05_01"             "c05_02"            
 [76] "c05_03"             "c05_05"             "c05_07"            
 [79] "c05_08"             "c05_13"             "c07_01"            
 [82] "c07_02"             "c07_03"             "c07_04"            
 [85] "c07_05"             "c07_06"             "c07_07"            
 [88] "c07_08"             "c08_02"             "c08_04"            
 [91] "c08_05"             "c10_01"             "c10_02"            
 [94] "c10_03"             "c13"                "c14_01"            
 [97] "c14_02"             "c15"                "c18_04"            
[100] "c18_05"             "c18_06"             "c18_07"            
[103] "c18_08"             "c18_09"             "c18_10"            
[106] "c18_11"             "c18_12"             "c18_13"            
[109] "c20"                "c20_otro"           "c22"               
[112] "c25"                "c30"                "c32_01"            
[115] "c32_02"             "c33"                "c34"               
[118] "c35_01"             "c35_02"             "c35_03"            
[121] "c35_04"             "c37_02"             "c37_04"            
[124] "c37_05"             "c37_09"             "c37_10"            
[127] "c38"                "c40_01"             "c40_02"            
[130] "c40_03"             "c40_04"             "c40_05"            
[133] "c40_06"             "c41_01"             "c41_02"            
[136] "c41_03"             "c41_04"             "c42_01"            
[139] "c42_02"             "c42_03"             "c42_04"            
[142] "c43"                "c44"                "c45"               
[145] "c46_01"             "c46_02"             "c46_03"            
[148] "c46_04"             "c47"                "c48"               
[151] "d01_01"             "d01_02"             "d01_03"            
[154] "d01_04"             "d03_01"             "d03_02"            
[157] "d04_01"             "d04_02"             "d05_01"            
[160] "d05_02"             "d05_03"             "d05_04"            
[163] "d06"                "d10"                "d11"               
[166] "d12"                "d16"                "d17"               
[169] "d18"                "d19"                "d20"               
[172] "d21"                "d22"                "d25_01"            
[175] "d25_02"             "d25_03"             "d25_04"            
[178] "d25_05"             "d25_06"             "d26_03"            
[181] "d26_04"             "d28"                "g01_01"            
[184] "g01_02"             "g01_03"             "g01_04"            
[187] "g01_05"             "g02_01"             "g02_02"            
[190] "g02_03"             "g02_04"             "g02_05"            
[193] "c19_01"             "c19_02"             "c19_03"            
[196] "c19_04"             "f01_05"             "f05_03"            
[199] "f05_04"             "f05_06"             "f05_07"            
[202] "s01"                "s02"                "s03"               
[205] "s04"                "s06"                "s07b"              
[208] "s08"                "s09"                "s10"               
[211] "s11_01"             "s11_02"             "s11_03"            
[214] "s11_04"             "s11_05"             "s11_06"            
[217] "s11_07"             "s11_08"             "s11_09"            
[220] "s12"                "s14"                "s31"               
[223] "m0_sexo"            "m0_edad"            "m01"               
[226] "m02"                "m03"                "ciuo08_m03"        
[229] "m04"                "ciiu4_m04"          "m05"               
[232] "m06"                "m07"                "m08"               
[235] "m09"                "m10"                "m11"               
[238] "m12"                "m13"                "m14b"              
[241] "m15"                "m16"                "m17"               
[244] "m18"                "m18_otro"           "m19"               
[247] "m20"                "m21"                "m22"               
[250] "ciuo08_m22"         "m23"                "ciiu4_m23"         
[253] "m24"                "m25"                "m26"               
[256] "m27"                "m28"                "m29"               
[259] "m30b"               "m31_02"             "m31_03"            
[262] "m32"                "m33"                "m33_otro"          
[265] "m36"                "m36_otro"           "m38"               
[268] "m38_otro"           "m39"                "m41"               
[271] "m42_01"             "m42_02"             "m42_03"            
[274] "m42_04"             "m42_04_otro"        "m43"               
[277] "m44"                "m54"                "m60"               
[280] "m61"                "m62"                "m63_01"            
[283] "m63_02"             "m63_03"             "m64_01"            
[286] "m64_02"             "m65"                "idencuestador"     
[289] "varios_enc"         "sexo_enc"           "edad_enc"          
[292] "nac_enc"            "educ_enc"           "exp_campo_enc"     
[295] "annio_entr"         "mes_entr"           "dia_entr"          
[298] "n_visitas_entr"     "inf_entr_dur"       "mod_t_dur"         
[301] "mod_r_dur"          "mod_c_dur"          "mod_d_dur"         
[304] "mod_f_dur"          "mod_g_dur"          "mod_s_dur"         
[307] "mod_m_dur"          "contacto_dur"       "presentacion_dur"  
[310] "consentimiento_dur" "superv"            </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(elsoc_2021) <span class="co"># Dimensiones</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2740  311</code></pre>
</div>
</div>
<p>Contamos con 311 variables (columnas) y 2740 observaciones (filas).</p>
<p>Ahora, realizaremos un pequeño procesamiento de nuestros datos con <code>dplyr</code> y <code>sjlabelled</code>, todo de una vez mediante el uso de pipes <code>%&gt;%</code>. Para recordar los pasos para el procesamiento de datos, revisar el <a href="https://descriptiva-facso.netlify.app/assignment/03-practico">curso anterior</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Procesemos la bbdd quedandonos solo con algunas variables de interés</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>proc_elsoc <span class="ot">&lt;-</span> elsoc_2021 <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>        idencuesta,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ing_per =</span> m13, </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ing_per_just =</span> m15,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">edad =</span> m0_edad, </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">mesfuerzo =</span> c18_09, </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">mtalento =</span> c18_10</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span>  <span class="co"># seleccionamos</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>        <span class="fu">across</span>(ing_per<span class="sc">:</span>mtalento, <span class="sc">~</span> <span class="fu">if_else</span>(. <span class="sc">%in%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">666</span>, <span class="sc">-</span><span class="dv">777</span>, <span class="sc">-</span><span class="dv">888</span>, <span class="sc">-</span><span class="dv">999</span>), <span class="cn">NA</span>, .)), <span class="co"># Recodificar a NA</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">pmerit =</span> (mesfuerzo <span class="sc">+</span> mtalento) <span class="sc">/</span> <span class="dv">2</span> <span class="co"># Crear nueva variable</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> <span class="co"># recodificamos y transformamos</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    labelled<span class="sc">::</span><span class="fu">set_variable_labels</span>(</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">pmerit =</span> <span class="st">"Promedio entre percepción de meritocracia por esfuerzo y talento"</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    ) <span class="co"># etiquetamos</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Veamos cómo quedó nuetras base procesada <code>proc_elsoc</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(proc_elsoc)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  idencuesta ing_per ing_per_just edad mesfuerzo mtalento pmerit
1    1101011      NA           NA   69         2        2      2
2    1101012      NA           NA   65         2        2      2
3    1101013      NA           NA   30         4        4      4
4    1101021  600000      1000000   55         3        3      3
5    1101023      NA      1000000   65         2        2      2
6    1101032      NA           NA   58         2        2      2</code></pre>
</div>
</div>
</section>
<section id="correlación-de-pearson" class="level1">
<h1>2. Correlación de Pearson</h1>
<section id="recordemos" class="level2">
<h2 class="anchored" data-anchor-id="recordemos">Recordemos…</h2>
<p>El coeficiente de correlación de Pearson es una medida estandarizada de covarianza que nos muestra la asociación <strong>lineal</strong> (sentido y fuerza) entre dos variables continuas. En otras palabras, nos permite conocer cómo y cuánto se relaciona la variación de una variable, con la variación de otra variable.</p>
<p>Sus valores oscilan entre -1 y 1, donde:</p>
<ul>
<li><p><span class="math inline">\(r\)</span> = 1: Correlación positiva perfecta. Cuando una variable aumenta, la otra también aumenta.</p></li>
<li><p><span class="math inline">\(r\)</span> = -1: Correlación negativa perfecta. Cuando una variable aumenta, la otra disminuye.</p></li>
<li><p><span class="math inline">\(r\)</span> = 0: No hay correlación lineal entre las variables. No hay una relación lineal discernible entre los cambios en las variables.</p></li>
</ul>
<p>Cuanto más cercano esté el valor de <span class="math inline">\(r\)</span> a 1 o -1, más fuerte será la correlación. Cuanto más cercano esté a 0, más débil será la correlación.</p>
<p><img src="../slides/img/scatters3.png" class="img-fluid"></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formula de la correlación
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
Correlacion = r = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})} {(n-1)\sigma_x \sigma_y }
\]</span></p>
</div>
</div>
</section>
</section>
<section id="ejemplo" class="level1">
<h1>Ejemplo</h1>
<p>El coeficiente de correlación de Pearson es una herramienta poderosa en investigación social, ya que nos permite cuantificar la relación entre dos fenómenos. Consideremos la siguiente pregunta: <em>¿Cómo se relacionan los ingresos que las personas reciben con los ingresos que creen que deberían recibir?</em></p>
<p>A partir de esta pregunta, podemos formular una hipótesis que guíe nuestra investigación: las personas con mayores ingresos podrían sentirse más justificadas en recibirlos, en función de su experiencia o habilidades. Por tanto, podríamos esperar una relación positiva entre los ingresos reales y los ingresos percibidos como merecidos. Dicho de otra forma:</p>
<blockquote class="blockquote">
<p>A medida que aumentan los ingresos reales de las personas, también aumentan los ingresos que creen merecer.</p>
</blockquote>
<p>Para poner a prueba esta hipótesis, utilizaremos las variables <code>ing_per</code> (ingresos) e <code>ing_per_just</code> (ingresos considerados justos) de la base de datos de ELSOC que previamente procesamos (<code>proc_elsoc</code>)</p>
<p>En R, el coeficiente de correlación de Pearson se obtiene con la función <code>cor()</code> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> proc_elsoc<span class="sc">$</span>ing_per, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> proc_elsoc<span class="sc">$</span>ing_per_just, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4659845</code></pre>
</div>
</div>
<p>Tenemos que la correlación entre los ingresos de las personas (<code>ing_per</code>) y los ingresos que consideran merecer (<code>ing_per_just</code>) es de 0.47.</p>
</section>
<section id="tamaños-de-efecto" class="level1">
<h1>3. Tamaños de efecto</h1>
<p>¿Y cómo puedo saber si el valor de la correlación es alto, medio o bajo? Si bien la correlación no nos indica causalidad, si nos permite conocer la dirección y fuerza de asociación entre dos variables. Un estándar para determinar qué tan fuerte es dicha asociación en las ciencias sociales es el propuesto por Cohen (1988).</p>
<style>
  table {
    margin-left: auto; /* Ajustamos el margen izquierdo a automático */
    margin-right: auto; /* Ajustamos el margen derecho a automático */
    border-collapse: collapse;
    width: 60%;
    border: 2px solid black;
  }
  
  th, td {
    border: 1px solid #D3D3D3;
    padding: 8px;
    text-align: center;
  }
</style>
<table>
<tbody><tr>
<th class="cell-left">
r
</th>
<th class="cell-left">
Significado aproximado (Cohen 1988)
</th>
</tr>
<tr>
<td class="cell-left">
&lt; ±0.1 
</td>
<td class="cell-left">
Muy pequeño
</td>
</tr>
<tr>
<td class="cell-left">
±0.1–0.3
</td>
<td class="cell-left">
Pequeño
</td>
</tr>
<tr>
<td class="cell-left">
±0.3–0.5
</td>
<td class="cell-left">
Moderado
</td>
</tr>
<tr>
<td class="cell-left">
&gt;±0.5
</td>
<td class="cell-left">
Grande
</td>
</tr>
</tbody></table>
<p>Con estos criterios podemos interpretar de mejor manera nuestros resultados de correlación. Como se observa, mientras más alto (sea en + o -) el coeficiente, más juntos estarán los datos (puntos), mostrando un patrón.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03-practico_files/figure-html/correlation-grid-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="row d-flex justify-content-center">
<div class="col-md-6">
<div class="card bg-danger text-white">
<div class="card-body">
<p><strong>Interpretación</strong></p>
<p>Recordemos nuestro resultado al comienzo:</p>
<p>Tenemos que la correlación entre la variable de ingresos reales y los ingresos considerados justos es de 0.47. ¿Cómo interpreto esto?</p>
<p>Una manera recomendable es la siguiente:</p>
<p><em>El coeficiente de correlación de Pearson entre los ingresos reales y los ingresos considerados justos es <strong>positivo y moderado</strong> (r = 0.47) según Cohen (1988).</em></p>
</div>
</div>
</div>
</div>
</section>
<section id="diagramas-de-dispersión" class="level1">
<h1>4. Diagramas de dispersión</h1>
<p>Siempre es recomendable acompañar el valor de la correlación con una exploración gráfica de la distribución bivariada de los datos. El <strong>gráfico o diagrama de dispersión</strong> es una buena herramienta, ya que muestra la forma, la dirección y la fuerza de la relación entre dos variables cuantitativas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_scatter</span>(<span class="at">data =</span> proc_elsoc, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">x =</span> ing_per,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> ing_per_just)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-practico_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A raíz del gráfico observamos que:</p>
<ul>
<li>existe un patrón positivo en los datos, en tanto los puntos están juntos y muestran una tendencia ascendente</li>
<li>existen datos que se alejan del patrón y se podrían considerar extremos</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Recurso
</div>
</div>
<div class="callout-body-container callout-body">
<p>En el siguiente <a href="https://rpsychologist.com/correlation/">enlace</a> pueden visualizar la correlación para dos variables cambiando la fuerza y el sentido de esta, al mismo tiempo que les permite observar la varianza compartida entre ambas variables.</p>
</div>
</div>
</section>
<section id="inferencia-en-correlación" class="level1">
<h1>5. Inferencia en correlación</h1>
<p>En el contexto de la inferencia, <strong>la correlación</strong> nos permite <strong>determinar si existe (o no) una asociación estadísticamente significativa</strong> entre dos variables. En ese sentido, la lógica del contraste de hipótesis usando correlación es:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hipótesis en correlación
</div>
</div>
<div class="callout-body-container callout-body">
<p>Contrastamos la <em>hipótesis nula</em> (o de trabajo) de <em>no</em> asociación entre variables: <span class="math display">\[  H_{0}: \rho = 0 \]</span></p>
<p>En relación a una <em>hipótesis alternativa</em> sobre la existencia una asociación significativa entre variables:</p>
<p><span class="math display">\[  H_{A}: \rho \neq 0 \]</span></p>
</div>
</div>
<p>Retomemos nuestro ejemplo anterior a partir de la pregunta de investigación: <em>¿Cómo se relacionan los ingresos que las personas reciben con los ingresos que creen que deberían recibir?</em></p>
<p>Formulemos nuestra hipótesis de manera formal:</p>
<ul>
<li><span class="math inline">\(H_{0}\)</span>: <span class="math inline">\(cor(ingresos, ingresos_{justos})\)</span> <span class="math inline">\(=\)</span> <span class="math inline">\(0\)</span></li>
<li><span class="math inline">\(H_{A}\)</span>: <span class="math inline">\(cor(ingresos, ingresos_{justos})\)</span> <span class="math inline">\(\neq\)</span> <span class="math inline">\(0\)</span></li>
</ul>
<p>Volvamos a calcular el coeficiente para estas dos variables. Anteriormente utilizamos la función <code>cor()</code> que nos entrega la magnitud del coeficiente, pero no nos entrega información respecto a su significancia estadística. Para ello, utilizaremos la función <code>cor.test()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>cor_results <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(<span class="at">x =</span> proc_elsoc<span class="sc">$</span>ing_per, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">y =</span> proc_elsoc<span class="sc">$</span>ing_per_just,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">method =</span> <span class="st">"pearson"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">use =</span> <span class="st">"complete.obs"</span>) <span class="co"># Considerar solo datos completos (listwise)</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>cor_results</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  proc_elsoc$ing_per and proc_elsoc$ing_per_just
t = 20.627, df = 1534, p-value &lt; 0.00000000000000022
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.4258942 0.5042486
sample estimates:
      cor 
0.4659845 </code></pre>
</div>
</div>
<p>Tenemos nuestro resultado, pero es poco amigable visualmente. Generemos una tabla para nuestra correlación.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>stats.table <span class="ot">&lt;-</span> <span class="fu">tidy</span>(cor_results)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>stats.table <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">estimate =</span> <span class="fu">round</span>(estimate, <span class="dv">2</span>),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">statistic =</span> <span class="fu">round</span>(statistic, <span class="dv">2</span>),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">ic_95 =</span> <span class="fu">paste0</span>(<span class="st">"["</span>, <span class="fu">round</span>(conf.low, <span class="dv">2</span>), <span class="st">","</span>, <span class="fu">round</span>(conf.high, <span class="dv">2</span>), <span class="st">"]"</span>),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">stars =</span> gtools<span class="sc">::</span><span class="fu">stars.pval</span>(p.value),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">p_value =</span> <span class="fu">case_when</span>(</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>            p.value <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="sc">&amp;</span> p.value <span class="sc">&gt;</span> <span class="fl">0.01</span> <span class="sc">~</span> <span class="st">"&lt; 0.05"</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>            p.value <span class="sc">&lt;</span> <span class="fl">0.01</span> <span class="sc">&amp;</span> p.value <span class="sc">&gt;</span> <span class="fl">0.001</span> <span class="sc">~</span> <span class="st">"&lt; 0.01"</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>            p.value <span class="sc">&lt;</span> <span class="fl">0.001</span> <span class="sc">~</span> <span class="st">"&lt; 0.001"</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>            <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">""</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">p_value =</span> <span class="fu">paste0</span>(p_value, stars)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(estimate, statistic, p_value, parameter, method, alternative, ic_95) <span class="sc">%&gt;%</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    kableExtra<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Estimación"</span>, <span class="st">"t"</span>, <span class="st">"p-value"</span>, <span class="st">"df"</span>, <span class="st">"Método"</span>, <span class="st">"Alternativa"</span>, <span class="st">"95% IC"</span>),</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">booktabs =</span> T</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>    kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>, <span class="st">"responsive"</span>),</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">full_width =</span> T,</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>        <span class="at">latex_options =</span> <span class="st">"hold_position"</span>,</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>        <span class="at">position =</span> <span class="st">"center"</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimación</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Método</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Alternativa</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">95% IC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">20.63</td>
<td style="text-align: left;">&lt; 0.001***</td>
<td style="text-align: right;">1534</td>
<td style="text-align: left;">Pearson's product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
<td style="text-align: left;">[0.43,0.5]</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Ya sabemos interpretar una correlación, ahora usemos este resultado para probar nuestra hipótesis:</p>
<blockquote class="blockquote">
<p>La asociación entre los ingresos reales y los ingresos justos es positiva, moderada y estadísticamente significativa (r = 0.47, p &lt; .001). Por tanto, con un 95% de confianza se puede rechazar la <span class="math inline">\(H_{0}\)</span> de no asociación entre variables, existiendo evidencia a favor de la <span class="math inline">\(H_{A}\)</span> sobre una asociación significativa entre los ingresos reales y los ingresos justos.</p>
</blockquote>
</section>
<section id="coeficiente-de-determinación-r2" class="level1">
<h1>6. Coeficiente de determinación (<span class="math inline">\(R^2\)</span>)</h1>
<p>El coeficiente de determinación <span class="math inline">\(R^2\)</span> es una medida estadística que indica la proporción de la varianza total de una variable que es explicada por otra(s) variable(s). En pocas palabras,</p>
<ul>
<li>se utiliza para evaluar cuánta de la variabilidad de una variable se debe a otra variable.</li>
<li>sus valores van desde 0 a 1, en donde 0 indica que ambas variables comparten el 0% de su varianza, y 1 que comparten el 100% de su varianza.</li>
</ul>
<p>En el contexto de la correlación entre <strong>solo dos variables</strong>, el <span class="math inline">\(R^2\)</span> es igual a elevar al cuadrado el coeficiente de correlación = <code>(r)^2</code>. Esto nos permite conocer qué tanto la variabilidad de una variable X estaría asociado a la variabilidad de otra variable Y.</p>
<p>En nuestro ejemplo anterior entre los ingresos reales y los ingresos justos, teníamos que su coeficiente de correlación era <span class="math inline">\(r = 0.47\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>coef_r <span class="ot">&lt;-</span> cor_results<span class="sc">$</span>estimate</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>coef_r</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      cor 
0.4659845 </code></pre>
</div>
</div>
<p>Calculemos el <span class="math inline">\(R^2\)</span> de esta asociación.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>coef_r<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      cor 
0.2171416 </code></pre>
</div>
</div>
<p>Con esto, podemos decir que el 21.7% de la variabilidad del ingreso real es compartido con la variabilidad de los ingresos justos.</p>
</section>
<section id="limitaciones-de-la-correlación-de-pearson" class="level1">
<h1>7. Limitaciones de la correlación de Pearson</h1>
<p>Como vimos en clases, el coeficiente de correlación de Pearson tiene una serie de limitaciones. Veamos como se reflejan algunas de estas en la práctica.</p>
<p>Para ejemplificar, tomaremos dos de las limitaciones más conocidas: <strong>(a) el coeficiente de correlación de Pearson es sensible a valores extremos; (b) puede reflejar distribuciones bivariadas distintas</strong>.</p>
<section id="a-valores-extremos" class="level2">
<h2 class="anchored" data-anchor-id="a-valores-extremos">(a) Valores extremos</h2>
<p>Anteriormente, observamos valores extremos en el diagrama de dispersión de nuestro ejemplo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_scatter</span>(<span class="at">data =</span> proc_elsoc, </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">x =</span> ing_per, </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> ing_per_just) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="st">"← Ingresos = 750.000 e Ingresos justos = 50.000.000"</span>),</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">x =</span> <span class="dv">5500000</span>, </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> <span class="dv">50100000</span>, </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">size =</span> <span class="dv">3</span>, </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">hjust =</span> <span class="dv">1</span>, </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"black"</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>                 )</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-practico_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vemos que el punto más extremo en el <em>eje y</em> corresponde a un caso que reporta que sus ingresos mensuales son de $750.000 y los ingresos que considera merecer son $50.000.000 ¿Cambiaría el coeficiente si eliminamos este valor de la base de datos?</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sobre eliminar valores…
</div>
</div>
<div class="callout-body-container callout-body">
<p>La decisión de eliminar uno o más de valores específicos de una base de datos debe estar justificada. Generalmente, estas decisiones están basadas en posibles errores técnicos con el dato, por ejemplo, un error de digitación.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Encuentra el punto con el valor máximo de ing_per_just</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>max_ing_per_just <span class="ot">&lt;-</span> proc_elsoc <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">filter</span>(ing_per_just <span class="sc">==</span> <span class="fu">max</span>(ing_per_just, <span class="at">na.rm =</span> T))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Excluye este caso de proc_elsoc</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>proc_elsoc2 <span class="ot">&lt;-</span> proc_elsoc <span class="sc">%&gt;%</span> </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="sc">!</span>idencuesta <span class="sc">%in%</span> max_ing_per_just<span class="sc">$</span>idencuesta)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular coeficiente</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> proc_elsoc2<span class="sc">$</span>ing_per, </span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> proc_elsoc2<span class="sc">$</span>ing_per_just, </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8479801</code></pre>
</div>
</div>
<p>Vemos ahora que el coeficente de correlación entre los ingresos reales y los ingresos considerados justos es de 0.85.</p>
<p>Visualicemos nuevamente sin este caso extremo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_scatter</span>(<span class="at">data =</span> proc_elsoc2, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">x =</span> ing_per, </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> ing_per_just)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-practico_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Al eliminar este caso extremo, se facilita la identificación del patrón subyacente en la relación entre las variables, revelando una asociación positiva fuerte. Este caso, que mostraba una gran discrepancia entre los ingresos reales y los ingresos percibidos como justos, estaba afectando significativamente el análisis, reduciendo el coeficiente de correlación a casi la mitad de su valor original.</p>
<p>Esto <strong>ilustra cómo un solo valor atípico puede distorsionar nuestras conclusiones sobre la fuerza y dirección de la relación entre dos variables</strong>.</p>
</section>
<section id="b-distintas-distribuciones" class="level2">
<h2 class="anchored" data-anchor-id="b-distintas-distribuciones">(b) Distintas distribuciones</h2>
<p>Otra de las limitaciones más conocidas del coeficiente de correlación es que un mismo valor puede representar distintas distribuciones de datos. El mejor ejemplo de esta limitación es el cuarteto de Anscombe, que muestra cuatro conjuntos de datos con las mismas propiedades estadísticas (media, mediana y varianza), pero con distribuciones muy diferentes.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-practico_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A pesar de tener las mismas propiedades estadísticas, los cuatro conjuntos producen el mismo coeficiente de correlación (<span class="math inline">\(r = 0.82\)</span>). Esto podría llevarnos a esperar que las distribuciones sean similares, pero el cuarteto de Anscombe demuestra lo contrario: <strong>el mismo coeficiente de correlación no implica que los conjuntos de datos tengan una distribución bivariada similar.</strong></p>
<p>Este ejemplo subraya la importancia de complementar los análisis estadísticos (como el coeficiente de correlación) con visualizaciones de los datos para tener una mejor comprensión de las relaciones entre las variables.</p>
</section>
</section>
<section id="ejercicio-autónomo" class="level1">
<h1>Ejercicio autónomo</h1>
<p>A partir de la base de datos de <code>proc_elsoc</code> responda la siguiente pregunta <em>¿en qué medida la edad de las personas está asociadas a sus percepciones sobre la meritocracia?</em> Para responder esta pregunta siga los siguientes pasos:</p>
<ol type="1">
<li>Calcule el coeficiente de correlación de Pearson (<span class="math inline">\(r\)</span>) entre las variables <code>edad</code> y <code>pmerit</code>. <code>pmerit</code> es una variable que promedia las variables de <code>mesfuerzo</code> y <code>mtalento</code></li>
<li>Interprete el tamaño de efecto del coeficiente siguiendo los criterios de Cohen (1988)</li>
<li>Reporte el sentido de la dirección de la correlación</li>
<li>Interprete la significancia estadística del coeficiente</li>
<li>Visualice la relación entre las variables con un gráfico de dispersión y comente</li>
</ol>
</section>
<section id="resolución-ejercicio-autónomo" class="level1">
<h1>Resolución ejercicio autónomo</h1>
<p>Formulemos nuestra hipótesis de manera formal:</p>
<ul>
<li><span class="math inline">\(H_{0}\)</span>: <span class="math inline">\(cor(edad, pmerit)\)</span> <span class="math inline">\(=\)</span> <span class="math inline">\(0\)</span></li>
<li><span class="math inline">\(H_{A}\)</span>: <span class="math inline">\(cor(edad, pmerit)\)</span> <span class="math inline">\(\neq\)</span> <span class="math inline">\(0\)</span></li>
</ul>
<p>Para contestar los puntos 1,2,3 y 4 usaremos el comando <code>cor.test</code> para evaluar la correlación entre <code>edad</code> y <code>pmerit</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>results_ej <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(<span class="at">x =</span> proc_elsoc<span class="sc">$</span>edad, <span class="at">y =</span> proc_elsoc<span class="sc">$</span>pmerit, <span class="at">method =</span> <span class="st">"pearson"</span>, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>results_ej</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  proc_elsoc$edad and proc_elsoc$pmerit
t = 5.5057, df = 2700, p-value = 0.00000004023
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.06792922 0.14251033
sample estimates:
      cor 
0.1053679 </code></pre>
</div>
</div>
<p>Con este output podemos sostener lo siguiente:</p>
<blockquote class="blockquote">
<p>El coeficiente de correlación de Pearson entre la edad y el promedio de meritocracia es positivo y estadísticamente significativo (<span class="math inline">\(r\)</span> = 0.11, <span class="math inline">\(p\)</span> &lt; 0.001). Por tanto, con un 95% de confianza se puede rechazar la <span class="math inline">\(H_{0}\)</span> de no asociación entre variables, existiendo evidencia a favor de la <span class="math inline">\(H_{A}\)</span> sobre una asociación significativa entre la edad de las personas y su percepción de meritocracia.</p>
</blockquote>
<blockquote class="blockquote">
<p>Respecto al tamaño de este efecto, de acuerdo a los criterios de Cohen corresponde a un tamaño pequeño. Consistentemente, la varianza compartida (<span class="math inline">\(r²\)</span>) entre ambas variables es muy baja, correspondiendo a un 0.01%.</p>
</blockquote>
<p>Para contestar el punto 5 usaremos el comando <code>plot_scatter</code> para visualizar la asociación entre <code>edad</code> y <code>pmerit</code>.</p>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_scatter</span>(<span class="at">data =</span> proc_elsoc, </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">x =</span> edad, </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> pmerit)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-ej" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ej-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-practico_files/figure-html/fig-ej-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ej-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Scatterplot entre edad y percepción de meritocracia promedio
</figcaption>
</figure>
</div>
<p>De acuerdo con la <a href="#fig-ej" class="quarto-xref">Figura&nbsp;1</a>, podemos observar que no existe un claro patrón de asociación entre la <code>edad</code> y <code>pmerit</code>. En detalle, la nube de puntos muestra una distribución bivariada muy dispersa, por lo que es posible sostener que no hay una asociación lineal suficientemente fuerte. Esto, se puede respaldar en el coeficiente de correlación que obtuvimos antes <span class="math inline">\(r\)</span> = 0.11, ya que si bien es positivo es de un tamaño de efecto muy pequeño según los criteriores de Cohen (1988).</p>
<div class="row d-flex justify-content-center">
<div class="col-md-6">
<div class="card bg-danger text-white">
<div class="card-body">
<p><strong>A tener en cuenta en la interpretación</strong></p>
<ul>
<li><p>Los dos aspectos principales en la interpretación de una prueba estadística son la <strong>inferencia</strong> y el <strong>tamaño de efecto</strong></p></li>
<li><p>En la <strong>inferencia</strong> se comenta si existe evidencia significativa para rechazar la hipótesis nula de no asociación. Para ello se considera:</p>
<ul>
<li>el nombre de la prueba utilizada (Z, T, Pearson,Spearman, Chi2, etc),</li>
<li>el resultado del cálculo de esta prueba empírica con los datos (ej: t=2.60)</li>
<li>información adicional si corresponde en el cálculo (ej: grados de libertad)</li>
<li>el valor p correspondiente a la prueba empírica: si bien existe un nivel convencional de rechazo de Ho p&lt;0.05, en caso que el p sea menor que otros valores convencionales (p&lt;0.01 o p&lt;0.001) hay que mencionar los niveles con menor probabilidad de error.</li>
</ul></li>
<li><p>En el caso de <strong>tamaño de efecto</strong> hay que considerar aquellos específicos de cada prueba, por ejemplo criterios de Cohen y R2 para Pearson, o Phi/Cramer para Chi 2.</p></li>
</ul>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/correlacional\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Content <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2024 by <a href="https://www.jc-castillo.com">Juan Castillo</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/cursos-metodos-facso/correlacional">View the source at <i class="fa-brands fa-github" aria-label="github"></i> GitHub</a></p>
</div>
  </div>
</footer>




</body></html>