<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Estadística Correlacional - Inferencia, asociación y reporte">

<title>Estadística Correlacional - Práctico 5: Asociación entre categóricas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="..//files/logo-correlacional-transp.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Estadística Correlacional - Práctico 5: Asociación entre categóricas">
<meta property="og:description" content="">
<meta property="og:image" content="https://correlacional.netlify.app/files/logo-correlacional.png">
<meta property="og:site_name" content="Estadística Correlacional">
<meta property="og:locale" content="es">
<meta property="og:image:height" content="533">
<meta property="og:image:width" content="466">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Estadística Correlacional</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../news/index.html"> 
<span class="menu-text">Informaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Planificación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../content/index.html"> 
<span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignment/index.html"> 
<span class="menu-text">Prácticos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resource/index.html"> 
<span class="menu-text">Recursos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://rstudio.cloud"> <i class="bi bi-cloud-fill" role="img" aria-label="RStudio.cloud">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#objetivo-de-la-práctica" id="toc-objetivo-de-la-práctica" class="nav-link active" data-scroll-target="#objetivo-de-la-práctica">Objetivo de la práctica</a></li>
  <li><a href="#pregunta-de-investigación" id="toc-pregunta-de-investigación" class="nav-link" data-scroll-target="#pregunta-de-investigación">1. Pregunta de investigación</a>
  <ul class="collapse">
  <li><a href="#recursos-de-la-práctica" id="toc-recursos-de-la-práctica" class="nav-link" data-scroll-target="#recursos-de-la-práctica">Recursos de la práctica</a></li>
  </ul></li>
  <li><a href="#datos-y-librerías" id="toc-datos-y-librerías" class="nav-link" data-scroll-target="#datos-y-librerías">2. Datos y librerías</a></li>
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis">3. Análisis</a>
  <ul class="collapse">
  <li><a href="#correlación-para-variables-nominales" id="toc-correlación-para-variables-nominales" class="nav-link" data-scroll-target="#correlación-para-variables-nominales">3.1 Correlación para variables nominales</a>
  <ul class="collapse">
  <li><a href="#correlación-punto-biserial" id="toc-correlación-punto-biserial" class="nav-link" data-scroll-target="#correlación-punto-biserial">3.1.1 Correlación punto biserial</a></li>
  <li><a href="#correlación-tetracorica" id="toc-correlación-tetracorica" class="nav-link" data-scroll-target="#correlación-tetracorica">3.1.2 Correlación tetracorica</a></li>
  </ul></li>
  <li><a href="#tablas-de-contingencia" id="toc-tablas-de-contingencia" class="nav-link" data-scroll-target="#tablas-de-contingencia">3.2 Tablas de contingencia</a></li>
  <li><a href="#prueba-de-hipótesis-con-chi-cuadrado-x2" id="toc-prueba-de-hipótesis-con-chi-cuadrado-x2" class="nav-link" data-scroll-target="#prueba-de-hipótesis-con-chi-cuadrado-x2">3.3. Prueba de hipótesis con Chi cuadrado (<span class="math inline">\(X^2\)</span>)</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">4. Conclusiones</a>
  <ul class="collapse">
  <li><a href="#pregunta-1" id="toc-pregunta-1" class="nav-link" data-scroll-target="#pregunta-1">Pregunta 1</a></li>
  </ul></li>
  <li><a href="#ejercicio-autónomo" id="toc-ejercicio-autónomo" class="nav-link" data-scroll-target="#ejercicio-autónomo">Ejercicio autónomo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header">
<h1 class="title display-7">Práctico 5: Asociación entre categóricas</h1>

<div class="date-block bg-assignment text-white p-2">
  <p class="date">Sesión del martes, 8 de octubre de 2024</p>
</div>
</header>


<section id="objetivo-de-la-práctica" class="level1">
<h1>Objetivo de la práctica</h1>
<p>El objetivo de esta guía práctica es introducir herramientas estadísticas para el análisis de relación entre variables categóricas (nominales).</p>
<p>En detalle, aprenderemos a:</p>
<ol type="1">
<li>Aplicar coeficientes de correlación entre variables categóricas (nominales-ordinales)</li>
<li>Generar y analizar tablas de contingencia (o cruzadas)</li>
<li>Estimar e interpretar la prueba de Chi-cuadrado (<span class="math inline">\(X^2\)</span>)</li>
</ol>
<p>En esta guía utilizaremos un ejemplo que desarrollaremos progresivamente para exponer los contenidos. Al final de esta guía se proporciona un ejercicio autónomo que deberá resolver de manera individual o grupal tomando como referencia el ejemplo aquí expuesto.</p>
</section>
<section id="pregunta-de-investigación" class="level1">
<h1>1. Pregunta de investigación</h1>
<p>La erradicación de la violencia es un objetivo compartido por múltiples países y organizaciones internacionales (World Health Organization, 2009, 2010, 2014). Sin embargo, la violencia no es un fenómeno que se pueda erradicar en el corto plazo, más bien es un fenómeno con el cual se debe coexistir planteando límites para su uso (Keane, 2004). Dicho de otra forma, coexistir con la violencia implica determinar las situaciones en que su uso estaría justificado. Las movilizaciones masivas del 2019 en Chile son un claro ejemplo de un evento donde distintos tipos de violencia fueron justificadas. Estas movilizaciones se caracterizaron por violaciones sistemáticas a los derechos humanos de parte de la policía (Amnistía Internacional, 2020), así como también por un alza en la cantidad de protesta violenta (Joignant et al., 2020). Ante este panorama, la violencia como forma de protesta tuvo un incremento en sus niveles de justificación, mientras que la justificación a la violencia policial disminuyó considerablemente (González et al., 2019). El ascenso en los niveles de justificación se torna especialmente relevante si se tiene en consideración que aquellos que justifican la violencia son más tendientes a ejercerla (Nunes et al., 2021), amenzando la convivencia pacífica al largo plazo (Gerber, Carvacho, et al., 2017). Ante esta problemática, se abren las interrogantes sobre ¿quienes y por qué justifican la violencia?</p>
<p>El estudio de las justificaciones de la violencia distingue si esta se ejerce por el cambio social o por el control social. En la literatura empírica se han ofrecido tres explicaciones. La primera es que quienes pertenecen a grupos desaventajados tienden a justificar actos violentos que buscan generar algún cambio en las estructuras jerárquicas de la sociedad. La segunda es que quienes poseen ideologías más cercanas al autoritarismo o a la dominancia social, tienden a justificar más la violencia que mantiene el status quo. La tercera es que quienes perciben que son tratados de manera injusta de parte de las autoridades, las legitiman menos y, por ende, justifican menos la violencia que estas ejerzan. Esta última explicación es la que ha recibido más desarrollo en el último tiempo, relevando el rol que tiene sentir injusticia en el trato en la justificación de la violencia. Sin embargo, en este estudio se parte de la premisa que la justicia no es un concepto unidimensional, sino uno multidimensional. A raíz de ello, se propone integrar a la justicia distributiva como una dimensión relevante para explicar las dinámicas de la justificación de la violencia, en tanto es un motivador de la acción humana a nivel micro y macro (Liebig, 2016). La pregunta de investigación que guía el estudio es:</p>
<p><strong>Pregunta 1</strong>: <em>¿En qué medida se relacionan el sentido de injusticia distributiva y la justificación de la violencia por el <strong>cambio social</strong> en Chile al año 2019?</em></p>
<blockquote class="blockquote">
<p>H1: A mayor sentido de injusticia distributiva, mayor es la justificación de la violencia por el cambio social</p>
</blockquote>
<p><strong>Pregunta 2</strong>: <em>¿En qué medida se relacionan el sentido de injusticia distributiva y la justificación de la violencia por el <strong>control social</strong> en Chile al año 2019?</em></p>
<blockquote class="blockquote">
<p>H2: A mayor sentido de injusticia distributiva, menor es la justificación de la violencia por el control social</p>
</blockquote>
<section id="recursos-de-la-práctica" class="level2">
<h2 class="anchored" data-anchor-id="recursos-de-la-práctica">Recursos de la práctica</h2>
<p>En esta práctica trabajaremos con un subconjunto de datos previamente procesados de la <a href="https://coes.cl/encuesta-panel/">Encuesta Social Longitudinal de Chile (ELSOC)</a> para Chile del año 2019. Para este ejercicio, obtendremos directamente esta base desde internet. No obstante, también es posible acceder a la misma información a través del siguiente enlace: <a href="https://github.com/cursos-metodos-facso/datos-ejemplos/raw/refs/heads/main/elsoc2019_jv.RData"><i class="fa-solid fa-table" aria-label="table"></i> <code>ELSOC 2019</code></a>. Desde allí, podrás descargar el archivo que contiene el subconjunto procesado de la base de datos ELSOC 2019.</p>
</section>
</section>
<section id="datos-y-librerías" class="level1">
<h1>2. Datos y librerías</h1>
<p>Comencemos por preparar nuestros datos. Iniciamos cargando las librerías necesarias.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, <span class="co"># Manipulacion datos</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               sjPlot, <span class="co"># Graficos y tablas</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               sjmisc, <span class="co"># Descriptivos</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               kableExtra, <span class="co"># Tablas</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>               psych, <span class="co"># Estadísticos</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>               broom) <span class="co"># Varios</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) <span class="co"># para desactivar notacion cientifica</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># para limpiar el entorno de trabajo</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cargamos los datos directamente desde internet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar bbdd desde internet</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://github.com/cursos-metodos-facso/datos-ejemplos/raw/refs/heads/main/elsoc2019_jv.RData"</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A continuación, exploramos el subset de datos <code>elsoc</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(elsoc) <span class="co"># Nombre de columnas</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "jv_control"                "jv_cambio"                
 [3] "salario_perc_ceo"          "salario_perc_obrero"      
 [5] "salario_just_ceo"          "salario_just_obrero"      
 [7] "ingreso_justo"             "ingreso"                  
 [9] "ingreso_tramos"            "educ"                     
[11] "ingreso_satisfact"         "sexo"                     
[13] "indigena"                  "sdo_soc_ideal"            
[15] "sdo_grupos_inferiores"     "sdo_oportunidades_iguales"
[17] "sdo_condiciones_iguales"   "rwa_gobierno_firme"       
[19] "rwa_mandatario_fuerte"     "rwa_valores_ninos"        
[21] "rwa_obediencia_discplina"  "trato_carab"              
[23] "edad"                      "pos_pol"                  
[25] "frec_marcha"               "conf_carab"               
[27] "sj_gerente"                "sj_gerente_rec"           
[29] "jv_cambio_rec"             "jv_control_rec"           </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(elsoc) <span class="co"># Dimensiones</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3417   30</code></pre>
</div>
</div>
<p>Contamos con 30 variables (columnas) y 3417 observaciones (filas).</p>
<p>Ahora, realizaremos un pequeño procesamiento de nuestros datos con <code>dplyr</code>, todo de una vez mediante el uso de pipes <code>%&gt;%</code>. Para recordar los pasos para el procesamiento de datos, revisar la guía práctica del <a href="https://descriptiva-facso.netlify.app/assignment/03-practico">curso de estadística descriptiva</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>proc_elsoc <span class="ot">&lt;-</span> elsoc <span class="sc">%&gt;%</span> <span class="co"># seleccionamos</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">starts_with</span>(<span class="st">"jv"</span>),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">starts_with</span>(<span class="st">"sj"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>      ) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ahora, exploremos estadísticos descriptivos de nuestra base procesada <code>proc_elsoc</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>proc_elsoc <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  sjmisc<span class="sc">::</span><span class="fu">descr</span>(<span class="at">show =</span> <span class="fu">c</span>(<span class="st">"label"</span>,<span class="st">"range"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"NA.prc"</span>, <span class="st">"n"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(.,<span class="st">"markdown"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 11%">
<col style="width: 48%">
<col style="width: 3%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">jv_control</td>
<td style="text-align: left;">Justificación de la violencia por el control social</td>
<td style="text-align: right;">3407</td>
<td style="text-align: right;">0.2926544</td>
<td style="text-align: right;">1.4029938</td>
<td style="text-align: right;">0.8712963</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">jv_cambio</td>
<td style="text-align: left;">Justificación de la violencia por el cambio social</td>
<td style="text-align: right;">3405</td>
<td style="text-align: right;">0.3511853</td>
<td style="text-align: right;">1.4763583</td>
<td style="text-align: right;">0.9551252</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">jv_cambio_rec</td>
<td style="text-align: left;">Justificación de la violencia por el cambio social (binario)</td>
<td style="text-align: right;">3405</td>
<td style="text-align: right;">0.3511853</td>
<td style="text-align: right;">0.2499266</td>
<td style="text-align: right;">0.4330339</td>
<td style="text-align: left;">1 (0-1)</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">jv_control_rec</td>
<td style="text-align: left;">Justificación de la violencia por el control social (binario)</td>
<td style="text-align: right;">3407</td>
<td style="text-align: right;">0.2926544</td>
<td style="text-align: right;">0.2180804</td>
<td style="text-align: right;">0.4130029</td>
<td style="text-align: left;">1 (0-1)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">sj_gerente</td>
<td style="text-align: left;">Sentido de ijusticia gerente</td>
<td style="text-align: right;">3238</td>
<td style="text-align: right;">5.2385133</td>
<td style="text-align: right;">1.1668125</td>
<td style="text-align: right;">0.9492177</td>
<td style="text-align: left;">6.21 (0-6.21)</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">sj_gerente_rec</td>
<td style="text-align: left;">Sentido de injusticia gerente (binario)</td>
<td style="text-align: right;">3238</td>
<td style="text-align: right;">5.2385133</td>
<td style="text-align: right;">0.8903644</td>
<td style="text-align: right;">0.3124832</td>
<td style="text-align: left;">1 (0-1)</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="análisis" class="level1">
<h1>3. Análisis</h1>
<p>En <a href="https://www.gesis.org/en/issp/data-and-documentation/social-inequality/2009">ELSOC 2019</a> la justificación de la violencia se mide con una escala que incluye distintas situaciones de violencia. Nosotros tomaremos dos items:</p>
<style>
  table {
    margin-left: auto; /* Ajustamos el margen izquierdo a automático */
    margin-right: auto; /* Ajustamos el margen derecho a automático */
    border-collapse: collapse;
    width: 60%;
    border: 2px solid black;
  }
  
  th, td {
    border: 1px solid #D3D3D3;
    padding: 8px;
    text-align: center;
  }
</style>
<p><strong>Justificación de la violencia</strong>: <em>F05 ¿En qué medida cree usted que se justifican o no se justifican las siguientes situaciones?</em></p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Ítem</th>
<th style="text-align: center;">Categorías de respuesta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">F05_03 Que Carabineros use la fuerza para reprimir una manifestación pacífica</td>
<td style="text-align: center;">Nunca se justifica (1); Pocas veces se justifica (2); Algunas veces de justifica (3); Muchas veces se justifica (4); Siempre se justifica (5)</td>
</tr>
<tr class="even">
<td style="text-align: center;">F05_07 Que estudiantes tiren piedras a Carabineros en una marcha por la educación del país</td>
<td style="text-align: center;">Nunca se justifica (1); Pocas veces se justifica (2); Algunas veces de justifica (3); Muchas veces se justifica (4); Siempre se justifica (5)</td>
</tr>
</tbody>
</table>
<p>Originalmente, esta variable es ordinal, sin embargo, para efectos del ejemplo de este práctico, trabajaremos con la variable recodificada de la siguiente manera:</p>
<ul>
<li><strong>Justifica (1)</strong> = Pocas veces se justifica (2); Algunas veces de justifica (3); Muchas veces se justifica (4); Siempre se justifica (5)</li>
<li><strong>No justifica (0)</strong> = Nunca se justifica (1)</li>
</ul>
<p>Por otro lado, el <strong>sentido de injusticia distribuva</strong> se mide con un indicador denominado <em>evaluación de injusticia</em> (Jasso, 1980). Este representa cuanta justicia evalúan las personas en la distribución de recompensas de una situación. En este caso, representa la evalaución de qué tan justa es la distribución de ingresos de <em>un gerente hipótetico</em>, en tanto este representa el extremo mayor del espectro ocupacional. El indicador (en una versión simplificada) se lee de la siguiente manera:</p>
<blockquote class="blockquote">
<p>A mayor valor, los gerentes están más injustamente sobrerecompensados (se evalúa más injusticia en su situación)</p>
</blockquote>
<section id="correlación-para-variables-nominales" class="level2">
<h2 class="anchored" data-anchor-id="correlación-para-variables-nominales">3.1 Correlación para variables nominales</h2>
<section id="correlación-punto-biserial" class="level3">
<h3 class="anchored" data-anchor-id="correlación-punto-biserial">3.1.1 Correlación punto biserial</h3>
<p>La correlación punto biserial es una extensión del coeficiente de correlación de Pearson y se utiliza cuando una de las variables de estudio tienen un nivel de medición intervalar y la otra un nivel de medición nominal.</p>
<ul>
<li>El nombre de <em>punto biserial</em> es una forma de diferenciarla de la correlación de Pearson</li>
<li>Esta diferenciación es importante ya que nos prevee de que hay que tener consideraciones con su interpretación, particularmente en lo que refiere al <em>sentido</em></li>
<li>En lo que respecta a la <em>magnitud/tamaño</em> y la <em>inferencia</em>, sigue la misma lógica que hemos visto con la correlación de Pearson</li>
</ul>
<p>Para calcular este coeficiente en R utilizamos una función ya conocida: <code>cor.test()</code>. Probemoslo con las variables <code>jv_cambio_rec</code> y <code>sj_gerente</code>.</p>
<p>Primero, veamos la frecuencia de <code>jv_cambio_rec</code> y <code>sj_gerente</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">frq</span>(proc_elsoc<span class="sc">$</span>jv_cambio_rec)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Justificación de la violencia por el cambio social (binario) (x) &lt;numeric&gt; </span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="do">## # total N=3417 valid N=3405 mean=0.25 sd=0.43</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Value |        Label |    N | Raw % | Valid % | Cum. %</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="do">## ------------------------------------------------------</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="do">##     0 | No justifica | 2554 | 74.74 |   75.01 |  75.01</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="do">##     1 |    Justifica |  851 | 24.90 |   24.99 | 100.00</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="do">##  &lt;NA&gt; |         &lt;NA&gt; |   12 |  0.35 |    &lt;NA&gt; |   &lt;NA&gt;</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(proc_elsoc<span class="sc">$</span>sj_gerente, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 1.166812</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Obtengamos la correlación punto biserial entre justificación de la violencia por el cambio social y evaluación de justicia para gerentes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(proc_elsoc<span class="sc">$</span>jv_cambio_rec, proc_elsoc<span class="sc">$</span>sj_gerente)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  proc_elsoc$jv_cambio_rec and proc_elsoc$sj_gerente
t = 6.4245, df = 3227, p-value = 0.0000000001517
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.07818705 0.14630484
sample estimates:
     cor 
0.112378 </code></pre>
</div>
</div>
<p>Vemos que la correlación entre el sentido de injusticia distributiva (<code>sj_gerente</code>) y la justificación de la violencia por el cambio social (<code>jv_cambio_rec</code>) es positiva, pequeña y estadísticamente significativa (<span class="math inline">\(r\)</span> = 0.11; <em>p &lt; 0.05</em>)</p>
</section>
<section id="correlación-tetracorica" class="level3">
<h3 class="anchored" data-anchor-id="correlación-tetracorica">3.1.2 Correlación tetracorica</h3>
<p>La correlación tetracórica también es una extensión del coeficiente de correlación de Pearson, con la diferencia de que se usa cuando amabs variables de estudio son nominales dicotomicas (2 valores).</p>
<ul>
<li>Se calcula en base a la frecuencias de cada combinación de valores (00,01,10,11).</li>
<li>Supone que ambas variables son continuas y normalmente distribuidas antes de la categorización</li>
</ul>
<p>Veamos como vería una correlación tetracórica entre nuestras variables de estudio. En este caso, vamos a usar <code>jv_cambio</code> que ya es dicotomica (1 = Justifica, 0 = No justifica) y una versión recodificada del sentido de injusticia <code>sj_gerente_rec</code> (1 = Injusto, 0 = Justo)</p>
<p>Primero, veamos las frecuencias entre <code>jv_cambio_rec</code> y <code>sj_gerente_rec</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">frq</span>(proc_elsoc<span class="sc">$</span>jv_cambio_rec)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Justificación de la violencia por el cambio social (binario) (x) &lt;numeric&gt; </span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="do">## # total N=3417 valid N=3405 mean=0.25 sd=0.43</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Value |        Label |    N | Raw % | Valid % | Cum. %</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="do">## ------------------------------------------------------</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="do">##     0 | No justifica | 2554 | 74.74 |   75.01 |  75.01</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="do">##     1 |    Justifica |  851 | 24.90 |   24.99 | 100.00</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="do">##  &lt;NA&gt; |         &lt;NA&gt; |   12 |  0.35 |    &lt;NA&gt; |   &lt;NA&gt;</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">frq</span>(proc_elsoc<span class="sc">$</span>sj_gerente_rec)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="do">## Sentido de injusticia gerente (binario) (x) &lt;numeric&gt; </span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="do">## # total N=3417 valid N=3238 mean=0.89 sd=0.31</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="do">## Value |   Label |    N | Raw % | Valid % | Cum. %</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="do">## -------------------------------------------------</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="do">##     0 |   Justo |  355 | 10.39 |   10.96 |  10.96</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="do">##     1 | Injusto | 2883 | 84.37 |   89.04 | 100.00</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="do">##  &lt;NA&gt; |    &lt;NA&gt; |  179 |  5.24 |    &lt;NA&gt; |   &lt;NA&gt;</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Obtengamos la correlación tetracórica entre <code>jv_cambio_rec</code> y <code>sj_gerente_rec</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>matriz <span class="ot">&lt;-</span> proc_elsoc <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(jv_cambio_rec, sj_gerente_rec) <span class="co"># creamos matriz con var de interes</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">tetrachoric</span>(matriz, <span class="at">na.rm =</span> T)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: psych::tetrachoric(x = matriz, na.rm = T)
tetrachoric correlation 
               jv_c_ sj_g_
jv_cambio_rec  1.00       
sj_gerente_rec 0.11  1.00 

 with tau of 
 jv_cambio_rec sj_gerente_rec 
          0.67          -1.23 </code></pre>
</div>
</div>
<p>Vemos que la correlación entre el sentido de injusticia distributiva recodificado (<code>sj_gerente_rec</code>) y la justificación de la violencia por el cambio social (<code>jv_cambio_rec</code>) es positiva, muy pequeña y estadísticamente significativa (<span class="math inline">\(r\)</span> = 0.11; <em>p &lt; 0.05</em>).</p>
</section>
</section>
<section id="tablas-de-contingencia" class="level2">
<h2 class="anchored" data-anchor-id="tablas-de-contingencia">3.2 Tablas de contingencia</h2>
<p>Las tablas de contingencia son herramientas estadísticas utilizadas para resumir y analizar la relación entre dos o más variables categóricas. Estas tablas muestran la frecuencia de diferentes combinaciones de categorías de las variables, facilitando la visualización de patrones o asociaciones.</p>
<p>Dicho de otra manera, podemos saber cuántos casos de una determinada categoría de la variable <span class="math inline">\(Y\)</span> ocurren conjuntamente con una determinada categoría de la variable <span class="math inline">\(X\)</span>.</p>
<p>Veamos una tabla con nuestro ejemplo usando el comando <code>sjtab</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>proc_elsoc <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  sjPlot<span class="sc">::</span><span class="fu">sjtab</span>(sj_gerente_rec,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>        jv_cambio_rec,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">show.row.prc=</span><span class="cn">TRUE</span>, <span class="co"># porcentaje fila</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">show.col.prc=</span><span class="cn">TRUE</span> <span class="co"># porcentaje columna</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Sentido de<br>injusticia gerente<br>(binario)</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">Justificación de la<br>violencia por el<br>cambio social<br>(binario)</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">No justifica</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Justifica</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Justo</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">285</span><br><span style="color:#333399;">80.7&nbsp;%</span><br><span style="color:#339933;">11.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">68</span><br><span style="color:#333399;">19.3&nbsp;%</span><br><span style="color:#339933;">8.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">353</span><br><span style="color:#333399;">100&nbsp;%</span><br><span style="color:#339933;">10.9&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Injusto</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2135</span><br><span style="color:#333399;">74.2&nbsp;%</span><br><span style="color:#339933;">88.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">741</span><br><span style="color:#333399;">25.8&nbsp;%</span><br><span style="color:#339933;">91.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">2876</span><br><span style="color:#333399;">100&nbsp;%</span><br><span style="color:#339933;">89.1&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">2420</span><br><span style="color:#333399;">74.9&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">809</span><br><span style="color:#333399;">25.1&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">3229</span><br><span style="color:#333399;">100&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">χ<sup>2</sup>=6.736 · df=1 · φ=0.047 · p=0.009</td> 
</tr>
 
</tbody></table>
</div>
</div>
<p>En esta tabla vemos que los porcentajes coloreados en azul corresponde a las filas y el verde el porcentaje que corresponde a las columnas. Utilizando esta información podemos decir, por ejemplo:</p>
<ul>
<li><p>El 25.8% de quienes consideran que los gerentes están injustamente recompensados justifica la violencia por el cambio social</p></li>
<li><p>El 91.6% de quienes justifican la violencia por el cambio social consideran que los gerentes están justamente recompensados</p></li>
</ul>
<p>Ahora, ¿cómo sabemos si hay asociación? Repliquemos el ejemplo que vimos en clases, utilizando nuestras variables. Imaginemos que tenemos una base de datos con <em>N = 100</em>.</p>
<p>Una distribución con evidencia “perfecta” para nuestra hipótesis alternativa se puede ver en la siguiente tabla:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>tab1 <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"html"</span>, <span class="at">align =</span> <span class="st">'r'</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Sentido (in)justicia"</span>, <span class="st">"No justifica violencia"</span>, <span class="st">"Justifica violencia"</span>, <span class="st">"Total"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>, <span class="st">"responsive"</span>), <span class="at">full_width =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">latex_options =</span> <span class="st">"hold_position"</span>, <span class="at">position =</span> <span class="st">"center"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Sentido (in)justicia</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No justifica violencia</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Justifica violencia</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Justo</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: right;">Injusto</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Total</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</div>
<p>En contraste, una distribución que representaría un caso perfecto de no asociación, se puede ver en la siguiente tabla:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>tab2 <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"html"</span>, <span class="at">align =</span> <span class="st">'r'</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Sentido (in)justicia"</span>, <span class="st">"No justifica violencia"</span>, <span class="st">"Justifica violencia"</span>, <span class="st">"Total"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>, <span class="st">"responsive"</span>), <span class="at">full_width =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">latex_options =</span> <span class="st">"hold_position"</span>, <span class="at">position =</span> <span class="st">"center"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Sentido (in)justicia</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No justifica violencia</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Justifica violencia</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Justo</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: right;">Injusto</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Total</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</div>
</section>
<section id="prueba-de-hipótesis-con-chi-cuadrado-x2" class="level2">
<h2 class="anchored" data-anchor-id="prueba-de-hipótesis-con-chi-cuadrado-x2">3.3. Prueba de hipótesis con Chi cuadrado (<span class="math inline">\(X^2\)</span>)</h2>
<p>Para determinar si existe una asociación significativa entre dos variables categóricas se utiliza la prueba de Chi-cudrado (<span class="math inline">\(X^2\)</span>). Esta se basa en un test de diferencia, donde se compara nuestra tabla de contingencia y una tabla donde no existe asociación entre variables (<span class="math inline">\(H_0\)</span>), que representa la hipótesis nula. <strong>La lógica detrás es que si nuestra tabla es significativamente distinta de una tabla sin asociación, entonces podemos rechazar la hipóteis nula</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prueba de Chi-cuadrado
</div>
</div>
<div class="callout-body-container callout-body">
<p>Contrastamos la <em>hipótesis nula</em> (o de trabajo) de que las variables son idenpendientes entre ellas: <span class="math display">\[  H_{0}: \pi_{fc} =  \pi_{f}\pi_{c} \]</span></p>
<p>En relación a una <em>hipótesis alternativa</em> sobre que las variables están relacionadas: <span class="math display">\[  H_{A}:  \pi_{fc} \neq  \pi_{f}\pi_{c} \]</span></p>
</div>
</div>
<p>En R, utilizamos la función <code>chisq.test()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>chi_results <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(proc_elsoc<span class="sc">$</span>sj_gerente_rec, proc_elsoc<span class="sc">$</span>jv_cambio_rec)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>chi_results</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  proc_elsoc$sj_gerente_rec and proc_elsoc$jv_cambio_rec
X-squared = 6.7357, df = 1, p-value = 0.00945</code></pre>
</div>
</div>
<p>Obtuvimos nuestro resultado, pero no es muy amigable a la vista. Generemos una tabla de calidad para que sea reportable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>stats.table <span class="ot">&lt;-</span> <span class="fu">tidy</span>(chi_results)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>stats.table <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">statistic =</span> <span class="fu">round</span>(statistic, <span class="dv">2</span>),</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">p_value =</span> <span class="fu">case_when</span>(</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>            p.value <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="sc">&amp;</span> p.value <span class="sc">&gt;</span> <span class="fl">0.01</span> <span class="sc">~</span> <span class="st">"&lt; 0.05*"</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>            p.value <span class="sc">&lt;</span> <span class="fl">0.01</span> <span class="sc">&amp;</span> p.value <span class="sc">&gt;</span> <span class="fl">0.001</span> <span class="sc">~</span> <span class="st">"&lt; 0.01**"</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>            p.value <span class="sc">&lt;</span> <span class="fl">0.001</span> <span class="sc">~</span> <span class="st">"&lt; 0.001***"</span>,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>            <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">""</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(statistic, p_value, parameter, method) <span class="sc">%&gt;%</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    kableExtra<span class="sc">::</span><span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"html"</span>,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"X2"</span>, <span class="st">"p-value"</span>, <span class="st">"df"</span>, <span class="st">"Método"</span>),</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">booktabs =</span> T,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"Prueba de Chi-cuadrado entre justificación de la violencia por cambio social e injusticia distributiva"</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>    kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>, <span class="st">"responsive"</span>),</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">full_width =</span> T,</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">latex_options =</span> <span class="st">"hold_position"</span>,</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">position =</span> <span class="st">"center"</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">column_spec</span>(<span class="dv">4</span>, <span class="at">width =</span> <span class="st">"8cm"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-chi" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-chi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;1: Prueba de Chi-cuadrado entre justificación de la violencia por cambio social e injusticia distributiva
</figcaption>
<div aria-describedby="tbl-chi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed do-not-create-environment cell table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">X2</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Método</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6.74</td>
<td style="text-align: left;">&lt; 0.01**</td>
<td style="text-align: right;">1</td>
<td style="text-align: left; width: 8cm;">Pearson's Chi-squared test with Yates' continuity correction</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</div>
</figure>
</div>
</div>
<p>A partir de estos resultados, podemos reportar lo siguiente:</p>
<blockquote class="blockquote">
<p>A raíz de la prueba de <span class="math inline">\(X^2\)</span>, vemos que existe evidencia para rechazar la hipótesis nula sobre no asociación, generando evidencia a favor de nuestra hipótesis alternativa sobre una asociación estadísticamente significativa entre el sentido de injusticia distributiva y la justificación de la violencia por el cambio social (<span class="math inline">\(X^2\)</span> = 6.736, <em>p &lt; 0.05</em>)</p>
</blockquote>
</section>
</section>
<section id="conclusiones" class="level1">
<h1>4. Conclusiones</h1>
<section id="pregunta-1" class="level3">
<h3 class="anchored" data-anchor-id="pregunta-1">Pregunta 1</h3>
<p><strong>Pregunta 1</strong>: <em>¿En qué medida se relacionan el sentido de injusticia distributiva y la justificación de la violencia por el <strong>cambio social</strong> en Chile al año 2019?</em></p>
<p>Para responder esta pregunta debemos emplear la técnica de Chi-cuadrado <span class="math inline">\(X^2\)</span> para contrastar la hipótesis respecto a que existe una asoción entre el sentido de injusticia distributiva y la justificación de la violencia por el <em>cambio social</em>, ya que ambas variables son categóricas (nominales).</p>
<p>De acuerdo con los resultados obtenidos en la <a href="#tbl-chi" class="quarto-xref">Tabla&nbsp;1</a>, existe una asociación estadísticamente significativa entre el sentido de injusticia distributiva y la justificación de la violencia por el cambio social (<span class="math inline">\(X^2\)</span> = 6.736, <em>p &lt; 0.05</em>). Con todo, podemos sostener que la justificación del uso de la violencia por motivos de cambio social se ve influida por el grado de injusticia distributiva en los ingresos.</p>
</section>
</section>
<section id="ejercicio-autónomo" class="level1">
<h1>Ejercicio autónomo</h1>
<p>A partir de la base de datos de <code>proc_elsoc</code> responda la pregunta 2 planteada al inicio de este ejercicio. Es decir: <em>¿En qué medida se relacionan el sentido de injusticia distributiva y la justificación de la violencia por el <strong>control social</strong> en Chile al año 2019?</em></p>
<ol type="1">
<li>Estime la correlación adecauda para <code>sj_gerente</code> y <code>jv_control_rec</code>.</li>
<li>Presente en una tabla de contingencia entre las variables <code>sj_gerente_rec</code> y <code>jv_control_rec</code>.</li>
<li>Calcule el estadístico de Chi cuadrado (<span class="math inline">\(X^2\)</span>) entre las variables <code>sj_gerente_rec</code> y <code>jv_control_rec</code>.</li>
<li>Interprete los resultados obtenidos. Responda la pregunta de investigación a raíz de los calculos desarrolaldos.</li>
</ol>
<section id="referencias" class="level4">
<h4 class="anchored" data-anchor-id="referencias">Referencias</h4>
<p>Amnistía Internacional. (2020). Ojos sobre Chile. Amnistía Internacional. Gerber, M., González, R., Carvacho, H., Jiménez-Moya, G., &amp; Jackson, J. (2017). On the justification of intergroup violence: The roles of procedural justice, police legitimacy and group identity in attitudes towards violence among indigenous people. Psychology of Violence, 8(3), 379–389. https://doi.org/10.1037/vio0000177 González, R., Bargsted, M., Carvacho, H., Miranda, D., Cerda, E., Mella, M., &amp; Plaza, A. (2019). Radiografía del cambio social: Análisis de Resultados Longitudinales Estudio Longitudinal Social de Chile. Centro de Estudios de Conflicto y Cohesión Social. Jasso, G. (1980). A New Theory of Distributive Justice. American Sociological Review, 45(1), 3–32. https://doi.org/https://www.jstor.org/stable/2095239 JSTOR Joignant, A., Garretón, M., Somma, N. M., &amp; Campos, T. (2020). Informe Anual: Observatorio de Conflictos 2020. Centro de Estudios de Conflicto y Cohesión Social COES. https://doi.org/10.13140/RG.2.2.20137.83048 Keane, J. (2004). Violence and Democracy (1st ed.). Cambridge University press. Liebig, S., &amp; Sauer, C. (2016). Sociology of justice. Handbook of social justice theory and research, 37-59. World Health Organization. (2009). Changing cultural and social norms that support violence. World Health Organization. (2010). Violence prevention: the evidence. World Health Organization. (2014). Global Status Report on Violence Prevention 2014.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/correlacional\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Content <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2024 by <a href="https://www.jc-castillo.com">Juan Castillo</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/cursos-metodos-facso/correlacional">View the source at <i class="fa-brands fa-github" aria-label="github"></i> GitHub</a></p>
</div>
  </div>
</footer>




</body></html>